# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed9bad0bdb19f636716ee0bc5ac1438a66503795d165316e4372c88c605446bea3c4c76812f24fffde720001447c12f8f59d972662bc3cd210bbabffcb8dddce

test:
  secret_key_base: 54eacf7efb17f8640e2a6b06bce7364cc557348bf7015d7f185fcfaac66599de5e16a8edbf729c5b28296ae9b24342da2bab255db4cddbcc00f7e9744a5eb25a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
